// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  itemId: __t.string(),
  sellerFid: __t.i64(),
  reserveWei: __t.string(),
  endsAtMs: __t.i64(),
  status: __t.string(),
  topBidWei: __t.option(__t.string()),
  topBidderFid: __t.option(__t.i64()),
  buyNowWei: __t.option(__t.string()),
  antiSnipeUsed: __t.bool(),
  createdAtMs: __t.i64(),
  finalizedAtMs: __t.option(__t.i64()),
});
