// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.10.0 (commit 1d576dc75ca066879f6d9ee4d156c5bce940bd31).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import BuyNow from "./buy_now_reducer";
export { BuyNow };
import CloseListingAndTransfer from "./close_listing_and_transfer_reducer";
export { CloseListingAndTransfer };
import CreateAuction from "./create_auction_reducer";
export { CreateAuction };
import CreateListing from "./create_listing_reducer";
export { CreateListing };
import FinalizeAuction from "./finalize_auction_reducer";
export { FinalizeAuction };
import GrantStarterPack from "./grant_starter_pack_reducer";
export { GrantStarterPack };
import InboxMarkRead from "./inbox_mark_read_reducer";
export { InboxMarkRead };
import LinkWallet from "./link_wallet_reducer";
export { LinkWallet };
import MarkTxUsed from "./mark_tx_used_reducer";
export { MarkTxUsed };
import PlaceBid from "./place_bid_reducer";
export { PlaceBid };
import PvpAccept from "./pvp_accept_reducer";
export { PvpAccept };
import PvpCreateChallenge from "./pvp_create_challenge_reducer";
export { PvpCreateChallenge };
import PvpSubmitResult from "./pvp_submit_result_reducer";
export { PvpSubmitResult };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import AuctionRow from "./auction_table";
export { AuctionRow };
import BidRow from "./bid_table";
export { BidRow };
import EventRow from "./event_table";
export { EventRow };
import IdempotencyRow from "./idempotency_table";
export { IdempotencyRow };
import InboxRow from "./inbox_table";
export { InboxRow };
import InventoryItemRow from "./inventory_item_table";
export { InventoryItemRow };
import ListingRow from "./listing_table";
export { ListingRow };
import PvpMatchRow from "./pvp_match_table";
export { PvpMatchRow };
import StarterClaimRow from "./starter_claim_table";
export { StarterClaimRow };
import TransactionUsedRow from "./transaction_used_table";
export { TransactionUsedRow };
import UserRow from "./user_table";
export { UserRow };
import WalletLinkRow from "./wallet_link_table";
export { WalletLinkRow };

// Import and reexport all types
import Auction from "./auction_type";
export { Auction };
import Bid from "./bid_type";
export { Bid };
import Event from "./event_type";
export { Event };
import Idempotency from "./idempotency_type";
export { Idempotency };
import Inbox from "./inbox_type";
export { Inbox };
import InventoryItem from "./inventory_item_type";
export { InventoryItem };
import Listing from "./listing_type";
export { Listing };
import PvpMatch from "./pvp_match_type";
export { PvpMatch };
import StarterClaim from "./starter_claim_type";
export { StarterClaim };
import TransactionUsed from "./transaction_used_type";
export { TransactionUsed };
import User from "./user_type";
export { User };
import WalletLink from "./wallet_link_type";
export { WalletLink };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'auction',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'auction_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AuctionRow),
  __table({
    name: 'bid',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'bid_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BidRow),
  __table({
    name: 'event',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventRow),
  __table({
    name: 'idempotency',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'idempotency_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, IdempotencyRow),
  __table({
    name: 'inbox',
    indexes: [
      { name: 'msg_id', algorithm: 'btree', columns: [
        'msgId',
      ] },
    ],
    constraints: [
      { name: 'inbox_msg_id_key', constraint: 'unique', columns: ['msgId'] },
    ],
  }, InboxRow),
  __table({
    name: 'inventory_item',
    indexes: [
      { name: 'item_id', algorithm: 'btree', columns: [
        'itemId',
      ] },
    ],
    constraints: [
      { name: 'inventory_item_item_id_key', constraint: 'unique', columns: ['itemId'] },
    ],
  }, InventoryItemRow),
  __table({
    name: 'listing',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'listing_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ListingRow),
  __table({
    name: 'pvp_match',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'pvp_match_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PvpMatchRow),
  __table({
    name: 'starter_claim',
    indexes: [
      { name: 'fid', algorithm: 'btree', columns: [
        'fid',
      ] },
    ],
    constraints: [
      { name: 'starter_claim_fid_key', constraint: 'unique', columns: ['fid'] },
    ],
  }, StarterClaimRow),
  __table({
    name: 'transaction_used',
    indexes: [
      { name: 'tx_hash', algorithm: 'btree', columns: [
        'txHash',
      ] },
    ],
    constraints: [
      { name: 'transaction_used_tx_hash_key', constraint: 'unique', columns: ['txHash'] },
    ],
  }, TransactionUsedRow),
  __table({
    name: 'user',
    indexes: [
      { name: 'fid', algorithm: 'btree', columns: [
        'fid',
      ] },
    ],
    constraints: [
      { name: 'user_fid_key', constraint: 'unique', columns: ['fid'] },
    ],
  }, UserRow),
  __table({
    name: 'wallet_link',
    indexes: [
      { name: 'address', algorithm: 'btree', columns: [
        'address',
      ] },
    ],
    constraints: [
      { name: 'wallet_link_address_key', constraint: 'unique', columns: ['address'] },
    ],
  }, WalletLinkRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("buy_now", BuyNow),
  __reducerSchema("close_listing_and_transfer", CloseListingAndTransfer),
  __reducerSchema("create_auction", CreateAuction),
  __reducerSchema("create_listing", CreateListing),
  __reducerSchema("finalize_auction", FinalizeAuction),
  __reducerSchema("grant_starter_pack", GrantStarterPack),
  __reducerSchema("inbox_mark_read", InboxMarkRead),
  __reducerSchema("link_wallet", LinkWallet),
  __reducerSchema("mark_tx_used", MarkTxUsed),
  __reducerSchema("place_bid", PlaceBid),
  __reducerSchema("pvp_accept", PvpAccept),
  __reducerSchema("pvp_create_challenge", PvpCreateChallenge),
  __reducerSchema("pvp_submit_result", PvpSubmitResult),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

