// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  challengerFid: __t.i64(),
  challengedFid: __t.i64(),
  status: __t.string(),
  createdAtMs: __t.i64(),
  acceptedAtMs: __t.option(__t.i64()),
  resultJson: __t.option(__t.string()),
});
